---

- name: Get Jenkins Repository
  command: wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

- name: Add Jenkins Repository
  command: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Update Packages
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    allow_unauthenticated: yes
    state: present

- name: Get Initial Admin Password
  fetch:
    src: /var/lib/jenkins/secrets/initialAdminPassword
    dest: ~/allspark/{{ inventory_hostname }}/jenkinsInitialAdminPassword.txt
